{'dire_team_id': 0,
 'lobby_type': 0,
 'match_id': 4930110086,
 'match_seq_num': 4136374009,
 'players': [{'hero': Hero(hero_id = 63),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 149001714)},
             {'hero': Hero(hero_id = 114),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 104510655)},
             {'hero': Hero(hero_id = 38),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 1017755282)},
             {'hero': Hero(hero_id = 28),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 113800579)},
             {'hero': Hero(hero_id = 42),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 1014502861)},
             {'hero': Hero(hero_id = 119),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 82609350)},
             {'hero': Hero(hero_id = 86),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 78312288)},
             {'hero': Hero(hero_id = 93),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 1019224145)},
             {'hero': Hero(hero_id = 20),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 151111311)},
             {'hero': Hero(hero_id = 104),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 266999212)}],
 'radiant_team_id': 0,
 'start_time': 1564260293}
 
 
 
 
 {'cluster': 185,
 'dire_buildings': {'barracks_status': 1,
                    'bot_ancient': 0,
                    'bot_melee': 0,
                    'bot_ranged': 0,
                    'bot_t1': 0,
                    'bot_t2': 0,
                    'bot_t3': 0,
                    'mid_melee': 0,
                    'mid_ranged': 0,
                    'mid_t1': 0,
                    'mid_t2': 0,
                    'mid_t3': 0,
                    'top_ancient': 0,
                    'top_melee': 1,
                    'top_ranged': 0,
                    'top_t1': 0,
                    'top_t2': 0,
                    'top_t3': 0,
                    'tower_status': 0},
 'dire_score': 27,
 'duration': 1444,
 'engine': 1,
 'first_blood_time': 2,
 'flags': 0,
 'game_mode': 23,
 'human_players': 10,
 'leagueid': 0,
 'lobby_type': 0,
 'match_id': 4958184826,
 'match_seq_num': 4159099770,
 'negative_votes': 0,
 'picks_bans': [{'hero': Hero(hero_id = 26),
                 'is_pick': False,
                 'order': 0,
                 'side': 'dire'},
                {'hero': Hero(hero_id = 112),
                 'is_pick': False,
                 'order': 1,
                 'side': 'dire'},
                {'hero': Hero(hero_id = 1),
                 'is_pick': False,
                 'order': 2,
                 'side': 'dire'},
                {'hero': Hero(hero_id = 44),
                 'is_pick': False,
                 'order': 3,
                 'side': 'dire'},
                {'hero': Hero(hero_id = 22),
                 'is_pick': False,
                 'order': 4,
                 'side': 'dire'}],
 'players': [{'ability_upgrades': [{'ability': Ability(ability_id = 5144),
                                    'level': 1,
                                    'time': 109},
                                   {'ability': Ability(ability_id = 5143),
                                    'level': 2,
                                    'time': 238},
                                   {'ability': Ability(ability_id = 5142),
                                    'level': 3,
                                    'time': 310},
                                   {'ability': Ability(ability_id = 5143),
                                    'level': 4,
                                    'time': 362},
                                   {'ability': Ability(ability_id = 5144),
                                    'level': 5,
                                    'time': 387},
                                   {'ability': Ability(ability_id = 5145),
                                    'level': 6,
                                    'time': 447},
                                   {'ability': Ability(ability_id = 5144),
                                    'level': 7,
                                    'time': 488},
                                   {'ability': Ability(ability_id = 5144),
                                    'level': 8,
                                    'time': 543},
                                   {'ability': Ability(ability_id = 5143),
                                    'level': 9,
                                    'time': 544},
                                   {'ability': Ability(ability_id = 6014),
                                    'level': 10,
                                    'time': 550},
                                   {'ability': Ability(ability_id = 5143),
                                    'level': 11,
                                    'time': 594},
                                   {'ability': Ability(ability_id = 5145),
                                    'level': 12,
                                    'time': 636},
                                   {'ability': Ability(ability_id = 5142),
                                    'level': 13,
                                    'time': 654},
                                   {'ability': Ability(ability_id = 5142),
                                    'level': 14,
                                    'time': 711},
                                   {'ability': Ability(ability_id = 7045),
                                    'level': 15,
                                    'time': 729},
                                   {'ability': Ability(ability_id = 5142),
                                    'level': 16,
                                    'time': 731},
                                   {'ability': Ability(ability_id = 5145),
                                    'level': 17,
                                    'time': 862},
                                   {'ability': Ability(ability_id = 6865),
                                    'level': 18,
                                    'time': 992},
                                   {'ability': Ability(ability_id = 6866),
                                    'level': 19,
                                    'time': 1288}],
              'additional_units': [],
              'assists': 19,
              'backpack': [Item(item_id = 0),
                           Item(item_id = 0),
                           Item(item_id = 0)],
              'deaths': 5,
              'denies': 3,
              'gold': 1786,
              'gold_per_min': 912,
              'gold_spent': 21135,
              'hero': Hero(hero_id = 32),
              'hero_damage': 30588,
              'hero_healing': 0,
              'inventory': [Item(item_id = 116),
                            Item(item_id = 174),
                            Item(item_id = 63),
                            Item(item_id = 135),
                            Item(item_id = 143),
                            Item(item_id = 168)],
              'kills': 7,
              'last_hits': 48,
              'leaver_status': 0,
              'level': 25,
              'scaled_hero_damage': 14490,
              'scaled_hero_healing': 0,
              'scaled_tower_damage': 257,
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 4294967295),
              'tower_damage': 410,
              'xp_per_min': 1496},
             {'ability_upgrades': [{'ability': Ability(ability_id = 5267),
                                    'level': 1,
                                    'time': 151},
                                   {'ability': Ability(ability_id = 5269),
                                    'level': 2,
                                    'time': 205},
                                   {'ability': Ability(ability_id = 5267),
                                    'level': 3,
                                    'time': 233},
                                   {'ability': Ability(ability_id = 5269),
                                    'level': 4,
                                    'time': 268},
                                   {'ability': Ability(ability_id = 5267),
                                    'level': 5,
                                    'time': 288},
                                   {'ability': Ability(ability_id = 5270),
                                    'level': 6,
                                    'time': 336},
                                   {'ability': Ability(ability_id = 5267),
                                    'level': 7,
                                    'time': 385},
                                   {'ability': Ability(ability_id = 5269),
                                    'level': 8,
                                    'time': 437},
                                   {'ability': Ability(ability_id = 5268),
                                    'level': 9,
                                    'time': 484},
                                   {'ability': Ability(ability_id = 5918),
                                    'level': 10,
                                    'time': 539},
                                   {'ability': Ability(ability_id = 5269),
                                    'level': 11,
                                    'time': 628},
                                   {'ability': Ability(ability_id = 5270),
                                    'level': 12,
                                    'time': 701},
                                   {'ability': Ability(ability_id = 5268),
                                    'level': 13,
                                    'time': 720},
                                   {'ability': Ability(ability_id = 5268),
                                    'level': 14,
                                    'time': 790},
                                   {'ability': Ability(ability_id = 6086),
                                    'level': 15,
                                    'time': 800},
                                   {'ability': Ability(ability_id = 5268),
                                    'level': 16,
                                    'time': 822},
                                   {'ability': Ability(ability_id = 5270),
                                    'level': 17,
                                    'time': 847},
                                   {'ability': Ability(ability_id = 6379),
                                    'level': 18,
                                    'time': 942},
                                   {'ability': Ability(ability_id = 6515),
                                    'level': 19,
                                    'time': 1061}],
              'additional_units': [],
              'assists': 7,
              'backpack': [Item(item_id = 0),
                           Item(item_id = 0),
                           Item(item_id = 0)],
              'deaths': 3,
              'denies': 8,
              'gold': 4922,
              'gold_per_min': 1092,
              'gold_spent': 22500,
              'hero': Hero(hero_id = 58),
              'hero_damage': 30723,
              'hero_healing': 1474,
              'inventory': [Item(item_id = 63),
                            Item(item_id = 121),
                            Item(item_id = 40),
                            Item(item_id = 108),
                            Item(item_id = 247),
                            Item(item_id = 263)],
              'kills': 10,
              'last_hits': 53,
              'leaver_status': 0,
              'level': 25,
              'scaled_hero_damage': 15756,
              'scaled_hero_healing': 615,
              'scaled_tower_damage': 3085,
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 4294967295),
              'tower_damage': 5631,
              'xp_per_min': 2011},
             {'ability_upgrades': [{'ability': Ability(ability_id = 5158),
                                    'level': 1,
                                    'time': 155},
                                   {'ability': Ability(ability_id = 5159),
                                    'level': 2,
                                    'time': 239},
                                   {'ability': Ability(ability_id = 5158),
                                    'level': 3,
                                    'time': 281},
                                   {'ability': Ability(ability_id = 5159),
                                    'level': 4,
                                    'time': 311},
                                   {'ability': Ability(ability_id = 5158),
                                    'level': 5,
                                    'time': 387},
                                   {'ability': Ability(ability_id = 5161),
                                    'level': 6,
                                    'time': 431},
                                   {'ability': Ability(ability_id = 5158),
                                    'level': 7,
                                    'time': 462},
                                   {'ability': Ability(ability_id = 5159),
                                    'level': 8,
                                    'time': 535},
                                   {'ability': Ability(ability_id = 5160),
                                    'level': 9,
                                    'time': 595},

4955747645
Print(screen,
                FigletText("Hey Python :3", "big" ),
                screen.height // 2, x = screen.width // 3,
                colour = Screen.COLOUR_BLACK,
                bg = Screen.COLOUR_BLACK,
                speed = 1)