{'dire_team_id': 0,
 'lobby_type': 0,
 'match_id': 4930110086,
 'match_seq_num': 4136374009,
 'players': [{'hero': Hero(hero_id = 63),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 149001714)},
             {'hero': Hero(hero_id = 114),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 104510655)},
             {'hero': Hero(hero_id = 38),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 1017755282)},
             {'hero': Hero(hero_id = 28),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 113800579)},
             {'hero': Hero(hero_id = 42),
              'side': 'radiant',
              'steam_account': SteamAccount(account_id = 1014502861)},
             {'hero': Hero(hero_id = 119),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 82609350)},
             {'hero': Hero(hero_id = 86),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 78312288)},
             {'hero': Hero(hero_id = 93),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 1019224145)},
             {'hero': Hero(hero_id = 20),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 151111311)},
             {'hero': Hero(hero_id = 104),
              'side': 'dire',
              'steam_account': SteamAccount(account_id = 266999212)}],
 'radiant_team_id': 0,
 'start_time': 1564260293}